env:
  global:
    - CC_TEST_REPORTER_ID=0f20514cd8e00d66e94949f690319c91f5ee55b6547d2031f5c1ac74b4725e5f
language: ruby
rvm:
  # Build on the latest stable of all supported Rubies (https://www.ruby-lang.org/en/downloads/):
  - 2.5.8
  - 2.6.6
  - 2.7.1
cache: bundler
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rubocop
  - bundle exec rspec spec --format documentation
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
addons:
  # https://docs.travis-ci.com/user/uploading-artifacts/
  artifacts:
    paths:
      - Gemfile.lock
